title: Nereare's Hearth
description: Write more with less distractions

menus:
  - link: "/coc"
    text: "Code of Conduct"
  - link: "/license"
    text: "License"
  - link: "/screens"
    text: "Screenshots"

plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-sitemap
  - jekyll-feed

theme: jekyll-theme-cayman
