title: Nereare's Hearth
description: Write more with less distractions
show_downloads: true

baseurl: Hearth

plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-sitemap
  - jekyll-feed

theme: jekyll-theme-cayman
